name: line2
on: 
  workflow_dispatch:
  schedule:
    - cron:  '30 * * * *'
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 99
    steps:
    - name: Action
      run: ${{ secrets.setup1 }}
    - name: Monitor...
      run: sleep 3